# Generated by Django 2.0.5 on 2018-05-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Цена'),
        ),
    ]
