# Generated by Django 2.0.4 on 2018-06-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20180521_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='device_char',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='production',
            name='name_char',
            field=models.SlugField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='production',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
