# Generated by Django 2.0.4 on 2018-07-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20180630_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='name_char',
            field=models.TextField(default=''),
        ),
    ]
