# Generated by Django 2.0.4 on 2018-07-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20180707_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='device_char',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='production',
            name='name_char',
            field=models.CharField(default='', max_length=32),
        ),
    ]
