# Generated by Django 2.0.4 on 2018-07-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_auto_20180708_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
