# Generated by Django 2.0.7 on 2018-07-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_productionimage_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
