# Generated by Django 2.0.5 on 2018-07-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_auto_20180726_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='device_char',
            field=models.TextField(default='', verbose_name='Текст к категории'),
        ),
        migrations.AlterField(
            model_name='production',
            name='name_char',
            field=models.CharField(default='', max_length=32, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='production',
            name='text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Текст про гриль'),
        ),
        migrations.AlterField(
            model_name='production',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Имя гриля'),
        ),
    ]
