# Generated by Django 2.0.5 on 2018-07-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_auto_20180729_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='device_char',
        ),
        migrations.RemoveField(
            model_name='production',
            name='name_char',
        ),
        migrations.RemoveField(
            model_name='production',
            name='text',
        ),
        migrations.AddField(
            model_name='production',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='production',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
