# Generated by Django 2.0.5 on 2018-05-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_novelties_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelties',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10, verbose_name='Цена'),
        ),
    ]
