# Generated by Django 2.0.5 on 2018-05-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180521_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
