# Generated by Django 2.0.4 on 2018-07-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelties',
            name='text',
            field=models.CharField(max_length=32),
        ),
    ]
