# Generated by Django 2.0.4 on 2018-07-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180707_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelties',
            name='price',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10, verbose_name='Цена'),
        ),
    ]
