# Generated by Django 2.0.5 on 2018-07-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180707_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='novelties',
            options={'verbose_name': 'Новинка', 'verbose_name_plural': 'Новинки'},
        ),
        migrations.AlterField(
            model_name='novelties',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='novelties',
            name='text',
            field=models.CharField(max_length=32, verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='novelties',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Имя продукта'),
        ),
    ]
