# Generated by Django 2.0.5 on 2018-07-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='фото сертификатов'),
        ),
    ]
