# Generated by Django 2.0.4 on 2018-07-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180708_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='productioninorder',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10, verbose_name='Итоговая цена'),
        ),
    ]
