# Generated by Django 2.0.4 on 2018-07-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20180709_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioninbasket',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
